version: "3"

services:
  xtednode0:
    container_name: xtednode0
    image: "xted/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-xted.log}
    volumes:
      - ./localnet-setup/node0/xted:/xtechain:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  xtednode1:
    container_name: xtednode1
    image: "xted/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-xted.log}
    volumes:
      - ./localnet-setup/node1/xted:/xtechain:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  xtednode2:
    container_name: xtednode2
    image: "xted/node"
    environment:
      - ID=2
      - LOG=${LOG:-xted.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/xted:/xtechain:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  xtednode3:
    container_name: xtednode3
    image: "xted/node"
    environment:
      - ID=3
      - LOG=${LOG:-xted.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/xted:/xtechain:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
